#!/bin/bash
set -e
case "$1" in
	configure)
          
    	# stop the server
        /etc/init.d/tomcat6 stop
        
    	# Edit /etc/default/tomcat6
    	conffile=/etc/default/tomcat6
        #changing user to ionadmin breaks the server - doesn't start
        #sed -i "s/.*TOMCAT6_USER.*/TOMCAT6_USER=ionadmin/" $conffile
	# change number of days logs are kept 
	sed -i "s/#LOGFILE_DAYS=14/LOGFILE_DAYS=3/g" $conffile
        sed -i 's/.*JAVA_OPTS="-Djava.awt.headless.*"/JAVA_OPTS="-Djava.awt.headless=true -Xms2048m -Xmx8096m -XX:MaxPermSize=512M"/' $conffile

	conffile=/var/lib/tomcat6/conf/logging.properties
        #changing log level to off by default... 
	sed -i "s/FINE/OFF/g" $conffile
        sed -i "s/INFO/OFF/g" $conffile
	# remove catalina.out file which can grow indefinitively
	sed -i "s/.handlers = 1catalina.org.apache.juli.FileHandler, java.util.logging.ConsoleHandler/.handlers = 1catalina.org.apache.juli.FileHandler/g" $conffile
	sed -i "s/#org.apache.catalina/org.apache.catalina/g" $conffile
	sed -i "s/org.apache.catalina.startup.ContextConfig.level/com.iontorrent.level/g" $conffile
		
	# enable the apache tomcat connector (port 8009) if we haven't already done so		
	conffile=/var/lib/tomcat6/conf/server.xml
	#<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />
	if ! grep "<!--port 8009 enabled by Ion. Edited by debian/postinst -->" $conffile  1>/dev/null ; then
		sed -i 's:\(<!-- Define an AJP 1.3 Connector on port 8009 -->\):\1\n<!--port 8009 enabled by Ion. Edited by debian/postinst -->\n<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />:'	$conffile		
	fi	
				
	
	# ion internal server configuration
	if [ -e /opt/ion/.ion-internal-server ]; then
		echo "Internal servers configuration option called: copying internal.war to torrentscout.war in /var/lib/tomcat6/webapps"
		
		rm /var/lib/tomcat6/webapps/torrentscout.war
		cp /var/lib/tomcat6/webapps/internal.war /var/lib/tomcat6/webapps/torrentscout.war
		
		# Edit /etc/tomcat6/tomcat-users.xml - but only for our internal version
		# Default has numerous commented-out example entries so here, we remove any existing
		# entries for tomcat user, and add our required entry outside of any comment tags.
		conffile=/etc/tomcat6/tomcat-users.xml
		# Delete any entries that conflict with ours
		sed -i '/.*<user username="tomcat" password="tomcat".*/d' $conffile        
		
		# Add ours outside of comment tags: search for opening tag and insert on line after.
		sed -i 's/\(<tomcat-users>\)/\1\n  <user username="tomcat" password="tomcat" roles="admin, manager, manager-gui"\/>/' $conffile        
		  
	fi
	
	if [ -f /var/lib/tomcat6/webapps/internal.war ]; then		
		rm /var/lib/tomcat6/webapps/internal.war
	fi
	 
	# If there is already an existing version of TSL, the folder must be deleted, otherwise the new .war file may
	# not be deployed!
	if [ -d /var/lib/tomcat6/webapps/TSL ]; then
		echo "found existing folder /var/lib/tomcat6/webapps/TSL, will remove it (otherwise .war may not deploy correctly)"
		rm -fr /var/lib/tomcat6/webapps/TSL
	fi
	if [ -d /var/lib/tomcat6/webapps/torrentscout ]; then
		echo "found existing folder /var/lib/tomcat6/webapps/torrentscout, will remove it (otherwise .war may not deploy correctly)"
		rm -fr /var/lib/tomcat6/webapps/torrentscout
	fi
	# ionadmin should have permissions to make changes if needed
	chmod go+rw /var/lib/tomcat6/webapps
	chmod go+rw /var/lib/tomcat6/webapps/*
			
	# (re) start the server		
	/etc/init.d/tomcat6 start
	
	# only if apache is actually installed - which may not be the case on compute nodes, for instance
	if [ -f /etc/init.d/apache2 ]; then		
		#enable mod jk
		a2enmod jk
		/etc/init.d/apache2 reload
	else
		echo "I see no apache installation. To get rid of the port 8080 numbers, please install apache and ion-jk:"			
	fi
    ;;
esac

exit 0
